2024-08-19 15:30:29.923 | INFO     | __main__:omprint:30 - Traceback (most recent call last):

2024-08-19 15:30:29.923 | INFO     | __main__:omprint:30 -   File "/home/t2ytuser/.pyenv/versions/3.11.9/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-08-19 15:30:29.924 | INFO     | __main__:omprint:30 -   File "/home/t2ytuser/.pyenv/versions/3.11.9/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-08-19 15:30:29.924 | INFO     | __main__:omprint:30 -   File "/home/t2ytuser/.pyenv/versions/3.11.9/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^

2024-08-19 15:30:29.924 | INFO     | __main__:omprint:30 -   File "/home/t2ytuser/.pyenv/versions/3.11.9/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-08-19 15:30:29.924 | INFO     | __main__:omprint:30 -   File "/home/t2ytuser/trivia/main.py", line 308, in process_request
    save_to_db(process_id, language, voice, line, num_questions, num_options, background_music, background_video, logo_path)

2024-08-19 15:30:29.925 | INFO     | __main__:omprint:30 - TypeError: save_to_db() missing 1 required positional argument: 'account_text'

